image: "python:3"

stages:
  - validate
  - test
  - deploy

before_script:
  - pip3 install --no-cache-dir
      flake8 
      google_auth_oauthlib 
      google-api-python-client
      pytest
      yapf

validate:
  stage: validate
  script:
    - make validate

test:
  stage: test
  script:
    - make test
